In [4]:
# SQLAlchemy
from sqlalchemy import create_engine, inspect
import pandas as pd
# Path to sqlite

# Path to sqlite
database_path = "../Data/wdi_kaggle.sqlite"

# Create an engine that can talk to the database
engine = create_engine(f"sqlite:///{database_path}")
#from sqlalchemy import inspect
for table_name in inspect(engine).get_table_names():
   print(table_name)

Country
CountryNotes
Footnotes
Indicators
Series
SeriesNotes

In [5]:
conn= engine.connect()
Country_df= pd.read_sql("select * from Country",conn)
CountryNotes_df= pd.read_sql("select * from Country",conn)
Footnotes_df= pd.read_sql("select * from Country",conn)
Indicators_df= pd.read_sql("select * from Country",conn)
Series_df= pd.read_sql("select * from Country",conn)
SeriesNotes_df= pd.read_sql("select * from Country",conn)

In [6]:
# Save all dataframes as csv files
Country_df.to_csv("out_put\Country.csv",index=False)
CountryNotes_df.to_csv("out_put\CountryNotes.csv",index=False)
Footnotes_df.to_csv("out_put\Footnotes.csv",index=False)
Indicators_df.to_csv("out_put\Indicators.csv",index=False)
Series_df.to_csv("out_put\Series.csv",index=False)
SeriesNotes_df.to_csv("out_put\SeriesNotes.csv",index=False)

In [7]:
Country_df.head()

,CountryCode,ShortName,TableName,LongName,Alpha2Code,CurrencyUnit,SpecialNotes,Region,IncomeGroup,Wb2Code,...,GovernmentAccountingConcept,ImfDataDisseminationStandard,LatestPopulationCensus,LatestHouseholdSurvey,SourceOfMostRecentIncomeAndExpenditureData,VitalRegistrationComplete,LatestAgriculturalCensus,LatestIndustrialData,LatestTradeData,LatestWaterWithdrawalData
0,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,...,Consolidated central government,General Data Dissemination System (GDDS),1979,"Multiple Indicator Cluster Survey (MICS), 2010/11","Integrated household survey (IHS), 2008",,2013/14,,2013,2000
1,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,,Europe & Central Asia,Upper middle income,AL,...,Budgetary central government,General Data Dissemination System (GDDS),2011,"Demographic and Health Survey (DHS), 2008/09",Living Standards Measurement Study Survey (LSM...,Yes,2012,2011,2013,2006
2,DZA,Algeria,Algeria,People's Democratic Republic of Algeria,DZ,Algerian dinar,,Middle East & North Africa,Upper middle income,DZ,...,Budgetary central government,General Data Dissemination System (GDDS),2008,"Multiple Indicator Cluster Survey (MICS), 2012","Integrated household survey (IHS), 1995",,,2010,2013,2001
3,ASM,American Samoa,American Samoa,American Samoa,AS,U.S. dollar,,East Asia & Pacific,Upper middle income,AS,...,,,2010,,,Yes,2007,,,
4,ADO,Andorra,Andorra,Principality of Andorra,AD,Euro,,Europe & Central Asia,High income: nonOECD,AD,...,,,2011. Population data compiled from administra...,,,Yes,,,2006,

In [41]:
len(Country_df)

247

In [8]:
CountryNotes_df.head()

,CountryCode,ShortName,TableName,LongName,Alpha2Code,CurrencyUnit,SpecialNotes,Region,IncomeGroup,Wb2Code,...,GovernmentAccountingConcept,ImfDataDisseminationStandard,LatestPopulationCensus,LatestHouseholdSurvey,SourceOfMostRecentIncomeAndExpenditureData,VitalRegistrationComplete,LatestAgriculturalCensus,LatestIndustrialData,LatestTradeData,LatestWaterWithdrawalData
0,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,...,Consolidated central government,General Data Dissemination System (GDDS),1979,"Multiple Indicator Cluster Survey (MICS), 2010/11","Integrated household survey (IHS), 2008",,2013/14,,2013,2000
1,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,,Europe & Central Asia,Upper middle income,AL,...,Budgetary central government,General Data Dissemination System (GDDS),2011,"Demographic and Health Survey (DHS), 2008/09",Living Standards Measurement Study Survey (LSM...,Yes,2012,2011,2013,2006
2,DZA,Algeria,Algeria,People's Democratic Republic of Algeria,DZ,Algerian dinar,,Middle East & North Africa,Upper middle income,DZ,...,Budgetary central government,General Data Dissemination System (GDDS),2008,"Multiple Indicator Cluster Survey (MICS), 2012","Integrated household survey (IHS), 1995",,,2010,2013,2001
3,ASM,American Samoa,American Samoa,American Samoa,AS,U.S. dollar,,East Asia & Pacific,Upper middle income,AS,...,,,2010,,,Yes,2007,,,
4,ADO,Andorra,Andorra,Principality of Andorra,AD,Euro,,Europe & Central Asia,High income: nonOECD,AD,...,,,2011. Population data compiled from administra...,,,Yes,,,2006,

In [9]:
Footnotes_df.head()

,CountryCode,ShortName,TableName,LongName,Alpha2Code,CurrencyUnit,SpecialNotes,Region,IncomeGroup,Wb2Code,...,GovernmentAccountingConcept,ImfDataDisseminationStandard,LatestPopulationCensus,LatestHouseholdSurvey,SourceOfMostRecentIncomeAndExpenditureData,VitalRegistrationComplete,LatestAgriculturalCensus,LatestIndustrialData,LatestTradeData,LatestWaterWithdrawalData
0,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,...,Consolidated central government,General Data Dissemination System (GDDS),1979,"Multiple Indicator Cluster Survey (MICS), 2010/11","Integrated household survey (IHS), 2008",,2013/14,,2013,2000
1,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,,Europe & Central Asia,Upper middle income,AL,...,Budgetary central government,General Data Dissemination System (GDDS),2011,"Demographic and Health Survey (DHS), 2008/09",Living Standards Measurement Study Survey (LSM...,Yes,2012,2011,2013,2006
2,DZA,Algeria,Algeria,People's Democratic Republic of Algeria,DZ,Algerian dinar,,Middle East & North Africa,Upper middle income,DZ,...,Budgetary central government,General Data Dissemination System (GDDS),2008,"Multiple Indicator Cluster Survey (MICS), 2012","Integrated household survey (IHS), 1995",,,2010,2013,2001
3,ASM,American Samoa,American Samoa,American Samoa,AS,U.S. dollar,,East Asia & Pacific,Upper middle income,AS,...,,,2010,,,Yes,2007,,,
4,ADO,Andorra,Andorra,Principality of Andorra,AD,Euro,,Europe & Central Asia,High income: nonOECD,AD,...,,,2011. Population data compiled from administra...,,,Yes,,,2006,

In [10]:
Series_df.head()

,CountryCode,ShortName,TableName,LongName,Alpha2Code,CurrencyUnit,SpecialNotes,Region,IncomeGroup,Wb2Code,...,GovernmentAccountingConcept,ImfDataDisseminationStandard,LatestPopulationCensus,LatestHouseholdSurvey,SourceOfMostRecentIncomeAndExpenditureData,VitalRegistrationComplete,LatestAgriculturalCensus,LatestIndustrialData,LatestTradeData,LatestWaterWithdrawalData
0,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,...,Consolidated central government,General Data Dissemination System (GDDS),1979,"Multiple Indicator Cluster Survey (MICS), 2010/11","Integrated household survey (IHS), 2008",,2013/14,,2013,2000
1,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,,Europe & Central Asia,Upper middle income,AL,...,Budgetary central government,General Data Dissemination System (GDDS),2011,"Demographic and Health Survey (DHS), 2008/09",Living Standards Measurement Study Survey (LSM...,Yes,2012,2011,2013,2006
2,DZA,Algeria,Algeria,People's Democratic Republic of Algeria,DZ,Algerian dinar,,Middle East & North Africa,Upper middle income,DZ,...,Budgetary central government,General Data Dissemination System (GDDS),2008,"Multiple Indicator Cluster Survey (MICS), 2012","Integrated household survey (IHS), 1995",,,2010,2013,2001
3,ASM,American Samoa,American Samoa,American Samoa,AS,U.S. dollar,,East Asia & Pacific,Upper middle income,AS,...,,,2010,,,Yes,2007,,,
4,ADO,Andorra,Andorra,Principality of Andorra,AD,Euro,,Europe & Central Asia,High income: nonOECD,AD,...,,,2011. Population data compiled from administra...,,,Yes,,,2006,

In [15]:
SeriesNotes_df.head()

,CountryCode,ShortName,TableName,LongName,Alpha2Code,CurrencyUnit,SpecialNotes,Region,IncomeGroup,Wb2Code,...,GovernmentAccountingConcept,ImfDataDisseminationStandard,LatestPopulationCensus,LatestHouseholdSurvey,SourceOfMostRecentIncomeAndExpenditureData,VitalRegistrationComplete,LatestAgriculturalCensus,LatestIndustrialData,LatestTradeData,LatestWaterWithdrawalData
0,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,...,Consolidated central government,General Data Dissemination System (GDDS),1979,"Multiple Indicator Cluster Survey (MICS), 2010/11","Integrated household survey (IHS), 2008",,2013/14,,2013,2000
1,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,,Europe & Central Asia,Upper middle income,AL,...,Budgetary central government,General Data Dissemination System (GDDS),2011,"Demographic and Health Survey (DHS), 2008/09",Living Standards Measurement Study Survey (LSM...,Yes,2012,2011,2013,2006
2,DZA,Algeria,Algeria,People's Democratic Republic of Algeria,DZ,Algerian dinar,,Middle East & North Africa,Upper middle income,DZ,...,Budgetary central government,General Data Dissemination System (GDDS),2008,"Multiple Indicator Cluster Survey (MICS), 2012","Integrated household survey (IHS), 1995",,,2010,2013,2001
3,ASM,American Samoa,American Samoa,American Samoa,AS,U.S. dollar,,East Asia & Pacific,Upper middle income,AS,...,,,2010,,,Yes,2007,,,
4,ADO,Andorra,Andorra,Principality of Andorra,AD,Euro,,Europe & Central Asia,High income: nonOECD,AD,...,,,2011. Population data compiled from administra...,,,Yes,,,2006,

In [16]:
list(Country_df)

['CountryCode',
 'ShortName',
 'TableName',
 'LongName',
 'Alpha2Code',
 'CurrencyUnit',
 'SpecialNotes',
 'Region',
 'IncomeGroup',
 'Wb2Code',
 'NationalAccountsBaseYear',
 'NationalAccountsReferenceYear',
 'SnaPriceValuation',
 'LendingCategory',
 'OtherGroups',
 'SystemOfNationalAccounts',
 'AlternativeConversionFactor',
 'PppSurveyYear',
 'BalanceOfPaymentsManualInUse',
 'ExternalDebtReportingStatus',
 'SystemOfTrade',
 'GovernmentAccountingConcept',
 'ImfDataDisseminationStandard',
 'LatestPopulationCensus',
 'LatestHouseholdSurvey',
 'SourceOfMostRecentIncomeAndExpenditureData',
 'VitalRegistrationComplete',
 'LatestAgriculturalCensus',
 'LatestIndustrialData',
 'LatestTradeData',
 'LatestWaterWithdrawalData']

In [17]:
list(CountryNotes_df)

['CountryCode',
 'ShortName',
 'TableName',
 'LongName',
 'Alpha2Code',
 'CurrencyUnit',
 'SpecialNotes',
 'Region',
 'IncomeGroup',
 'Wb2Code',
 'NationalAccountsBaseYear',
 'NationalAccountsReferenceYear',
 'SnaPriceValuation',
 'LendingCategory',
 'OtherGroups',
 'SystemOfNationalAccounts',
 'AlternativeConversionFactor',
 'PppSurveyYear',
 'BalanceOfPaymentsManualInUse',
 'ExternalDebtReportingStatus',
 'SystemOfTrade',
 'GovernmentAccountingConcept',
 'ImfDataDisseminationStandard',
 'LatestPopulationCensus',
 'LatestHouseholdSurvey',
 'SourceOfMostRecentIncomeAndExpenditureData',
 'VitalRegistrationComplete',
 'LatestAgriculturalCensus',
 'LatestIndustrialData',
 'LatestTradeData',
 'LatestWaterWithdrawalData']

In [47]:
list(Footnotes_df)

['CountryCode',
 'ShortName',
 'TableName',
 'LongName',
 'Alpha2Code',
 'CurrencyUnit',
 'SpecialNotes',
 'Region',
 'IncomeGroup',
 'Wb2Code',
 'NationalAccountsBaseYear',
 'NationalAccountsReferenceYear',
 'SnaPriceValuation',
 'LendingCategory',
 'OtherGroups',
 'SystemOfNationalAccounts',
 'AlternativeConversionFactor',
 'PppSurveyYear',
 'BalanceOfPaymentsManualInUse',
 'ExternalDebtReportingStatus',
 'SystemOfTrade',
 'GovernmentAccountingConcept',
 'ImfDataDisseminationStandard',
 'LatestPopulationCensus',
 'LatestHouseholdSurvey',
 'SourceOfMostRecentIncomeAndExpenditureData',
 'VitalRegistrationComplete',
 'LatestAgriculturalCensus',
 'LatestIndustrialData',
 'LatestTradeData',
 'LatestWaterWithdrawalData']

In [19]:
# list

['CountryCode',
 'ShortName',
 'TableName',
 'LongName',
 'Alpha2Code',
 'CurrencyUnit',
 'SpecialNotes',
 'Region',
 'IncomeGroup',
 'Wb2Code',
 'NationalAccountsBaseYear',
 'NationalAccountsReferenceYear',
 'SnaPriceValuation',
 'LendingCategory',
 'OtherGroups',
 'SystemOfNationalAccounts',
 'AlternativeConversionFactor',
 'PppSurveyYear',
 'BalanceOfPaymentsManualInUse',
 'ExternalDebtReportingStatus',
 'SystemOfTrade',
 'GovernmentAccountingConcept',
 'ImfDataDisseminationStandard',
 'LatestPopulationCensus',
 'LatestHouseholdSurvey',
 'SourceOfMostRecentIncomeAndExpenditureData',
 'VitalRegistrationComplete',
 'LatestAgriculturalCensus',
 'LatestIndustrialData',
 'LatestTradeData',
 'LatestWaterWithdrawalData']

In [20]:
list(Series_df)

['CountryCode',
 'ShortName',
 'TableName',
 'LongName',
 'Alpha2Code',
 'CurrencyUnit',
 'SpecialNotes',
 'Region',
 'IncomeGroup',
 'Wb2Code',
 'NationalAccountsBaseYear',
 'NationalAccountsReferenceYear',
 'SnaPriceValuation',
 'LendingCategory',
 'OtherGroups',
 'SystemOfNationalAccounts',
 'AlternativeConversionFactor',
 'PppSurveyYear',
 'BalanceOfPaymentsManualInUse',
 'ExternalDebtReportingStatus',
 'SystemOfTrade',
 'GovernmentAccountingConcept',
 'ImfDataDisseminationStandard',
 'LatestPopulationCensus',
 'LatestHouseholdSurvey',
 'SourceOfMostRecentIncomeAndExpenditureData',
 'VitalRegistrationComplete',
 'LatestAgriculturalCensus',
 'LatestIndustrialData',
 'LatestTradeData',
 'LatestWaterWithdrawalData']

In [21]:
list(SeriesNotes_df)

['CountryCode',
 'ShortName',
 'TableName',
 'LongName',
 'Alpha2Code',
 'CurrencyUnit',
 'SpecialNotes',
 'Region',
 'IncomeGroup',
 'Wb2Code',
 'NationalAccountsBaseYear',
 'NationalAccountsReferenceYear',
 'SnaPriceValuation',
 'LendingCategory',
 'OtherGroups',
 'SystemOfNationalAccounts',
 'AlternativeConversionFactor',
 'PppSurveyYear',
 'BalanceOfPaymentsManualInUse',
 'ExternalDebtReportingStatus',
 'SystemOfTrade',
 'GovernmentAccountingConcept',
 'ImfDataDisseminationStandard',
 'LatestPopulationCensus',
 'LatestHouseholdSurvey',
 'SourceOfMostRecentIncomeAndExpenditureData',
 'VitalRegistrationComplete',
 'LatestAgriculturalCensus',
 'LatestIndustrialData',
 'LatestTradeData',
 'LatestWaterWithdrawalData']

In [82]:
# Scrape table(Unemployment) from WDI website

url="http://wdi.worldbank.org/table/2.5#"
tables = pd.read_html(url)

In [83]:
tables = pd.read_html(url)

In [84]:
tables[1]

Empty DataFrame
Columns: [(Unnamed: 0_level_0, Unnamed: 0_level_1), (Unemployment, male (% of male labor force) (modeled ILO estimate), 2000), (Unemployment, male (% of male labor force) (modeled ILO estimate), 2017), (Unemployment, female (% of female labor force) (modeled ILO estimate), 2000), (Unemployment, female (% of female labor force) (modeled ILO estimate), 2017), (Unemployment, youth male (% of male labor force ages 15-24) (modeled ILO estimate), 2000), (Unemployment, youth male (% of male labor force ages 15-24) (modeled ILO estimate), 2017), (Unemployment, youth female (% of female labor force ages 15-24) (modeled ILO estimate), 2000), (Unemployment, youth female (% of female labor force ages 15-24) (modeled ILO estimate), 2017), (Unemployment with basic education (% of total labor force with basic education), 2014-17), (Unemployment with intermediate education (% of total labor force with intermediate education), 2014-17), (Unemployment with advanced education (% of total labor force with advanced education), 2014-17)]
Index: []

In [122]:
df1=tables[1]
columns = list(df1)
columns = [list(i) for i in columns]
columns

[['Unnamed: 0_level_0', 'Unnamed: 0_level_1'],
 ['Unemployment, male (% of male labor force) (modeled ILO estimate)', '2000'],
 ['Unemployment, male (% of male labor force) (modeled ILO estimate)', '2017'],
 ['Unemployment, female (% of female labor force) (modeled ILO estimate)',
  '2000'],
 ['Unemployment, female (% of female labor force) (modeled ILO estimate)',
  '2017'],
 ['Unemployment, youth male (% of male labor force ages 15-24) (modeled ILO estimate)',
  '2000'],
 ['Unemployment, youth male (% of male labor force ages 15-24) (modeled ILO estimate)',
  '2017'],
 ['Unemployment, youth female (% of female labor force ages 15-24) (modeled ILO estimate)',
  '2000'],
 ['Unemployment, youth female (% of female labor force ages 15-24) (modeled ILO estimate)',
  '2017'],
 ['Unemployment with basic education (% of total labor force with basic education)',
  '2014-17'],
 ['Unemployment with intermediate education (% of total labor force with intermediate education)',
  '2014-17'],
 ['Unemployment with advanced education (% of total labor force with advanced education)',
  '2014-17']]

In [123]:
# Moderate the columns
columns[0] ="ShortName"
for i in range(1,len(columns)):
    if i<8:
        columns[i] = columns[i][0].lstrip("Unemployment,").lstrip()+" " + columns[i][1]
    else:
        columns[i] = columns[i][0].lstrip("Unemployment with ")+" "+ "2014-2017"

In [124]:
columns

['ShortName',
 'male (% of male labor force) (modeled ILO estimate) 2000',
 'male (% of male labor force) (modeled ILO estimate) 2017',
 'female (% of female labor force) (modeled ILO estimate) 2000',
 'female (% of female labor force) (modeled ILO estimate) 2017',
 'youth male (% of male labor force ages 15-24) (modeled ILO estimate) 2000',
 'youth male (% of male labor force ages 15-24) (modeled ILO estimate) 2017',
 'youth female (% of female labor force ages 15-24) (modeled ILO estimate) 2000',
 ', youth female (% of female labor force ages 15-24) (modeled ILO estimate) 2014-2017',
 'basic education (% of total labor force with basic education) 2014-2017',
 'rmediate education (% of total labor force with intermediate education) 2014-2017',
 'advanced education (% of total labor force with advanced education) 2014-2017']

In [129]:
tables[2]

,0,1,2,3,4,5,6,7,8,9,10,11
0,Afghanistan,3.8,1.1,3.0,2.5,5.6,2.1,5.2,3.8,12.3,16.2,15.5
1,Albania,17.4,14.6,18.2,12.6,30.0,33.8,26.6,27.5,13.8,20.4,19.1
2,Algeria,29.8,10.0,29.7,21.1,51.3,26.6,47.1,45.5,..,..,..
3,American Samoa,..,..,..,..,..,..,..,..,..,..,..
4,Andorra,..,..,..,..,..,..,..,..,..,..,..
5,Angola,20.7,6.8,25.0,7.5,49.3,16.8,57.1,16.7,..,..,..
6,Antigua and Barbuda,..,..,..,..,..,..,..,..,..,..,..
7,Argentina,14.0,7.5,16.4,9.5,29.8,20.5,36.0,27.4,10.5,9.1,3.3
8,Armenia,8.2,18.1,14.7,17.5,11.7,30.3,15.3,46.3,17.4,17.7,17.8
9,Aruba,..,..,..,..,..,..,..,..,..,..,..
10,Australia,6.5,5.5,6.1,5.7,12.9,13.8,11.2,11.5,..,..,..
11,Austria,4.8,5.9,4.6,5.0,6.9,10.7,5.6,8.7,12.9,5.0,3.1
12,Azerbaijan,11.0,4.1,12.8,5.9,23.7,11.3,21.7,15.6,..,..,..
13,"Bahamas, The",6.2,10.6,8.2,14.4,12.4,20.6,19.4,34.4,..,..,..
14,Bahrain,0.3,0.3,3.7,3.4,1.6,2.0,10.2,12.1,..,..,..
15,Bangladesh,3.3,3.3,3.3,6.7,9.4,10.3,10.3,16.7,3.5,8.5,10.7
16,Barbados,7.4,9.1,11.4,9.9,18.2,26.8,24.1,30.7,..,..,..
17,Belarus,14.0,7.2,9.8,4.0,23.7,11.2,18.9,7.3,13.4,8.2,3.7
18,Belgium,5.3,7.1,8.3,7.1,12.9,20.2,18.3,18.0,13.8,7.1,4.3
19,Belize,7.0,4.7,17.8,15.4,13.6,10.5,31.3,34.3,6.5,9.6,3.9
20,Benin,1.1,2.0,0.5,2.3,1.2,4.2,0.7,4.6,..,..,..
21,Bermuda,..,..,..,..,..,..,..,..,..,..,..
22,Bhutan,1.3,1.6,2.3,3.0,5.0,7.6,6.7,11.4,..,..,..
23,Bolivia,2.9,2.8,4.1,3.8,5.7,6.5,8.7,8.9,2.8,5.0,6.4
24,Bosnia and Herzegovina,23.4,18.8,30.3,23.1,51.4,43.5,59.9,51.0,22.9,11.1,9.8
25,Botswana,14.8,14.4,17.3,21.4,30.6,30.1,36.0,44.0,..,..,..
26,Brazil,7.9,11.4,12.8,14.7,15.0,25.7,23.3,33.2,15.4,14.6,7.0
27,British Virgin Islands,..,..,..,..,..,..,..,..,..,..,..
28,Brunei Darussalam,4.4,8.8,7.3,10.0,16.0,30.0,20.8,29.9,10.4,9.9,7.5
29,Bulgaria,16.6,6.4,15.8,5.9,35.8,13.2,29.6,12.4,17.5,5.3,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...
234,IDA blend,4.0,4.4,5.9,6.2,8.4,12.5,8.2,13.6,..,..,..
235,IDA only,4.6,3.7,4.7,4.5,9.1,8.1,10.1,11.3,..,..,..
236,IDA total,4.4,3.9,5.0,5.0,8.9,9.6,9.5,12.0,..,..,..
237,Late-demographic dividend,5.3,5.3,5.2,5.1,11.6,13.5,12.1,14.4,..,..,..
238,Latin America & Caribbean,7.7,7.0,11.5,9.6,14.4,15.3,20.3,20.8,11.6,11.9,6.6
239,Latin America & Caribbean (excluding high income),7.2,7.0,11.1,9.7,13.0,14.9,18.9,20.5,11.9,12.3,6.9
240,Latin America & the Caribbean (IDA & IBRD coun...,7.8,7.1,11.6,9.7,14.4,15.4,20.4,21.0,11.6,11.9,6.6
241,Least developed countries: UN classification,4.6,3.6,4.9,4.4,9.5,8.1,10.2,10.9,..,..,..
242,Low & middle income,5.0,4.6,5.4,5.4,11.4,12.1,12.4,14.8,..,..,..
243,Low income,4.4,3.6,4.2,3.8,8.1,7.2,8.6,8.7,..,..,..
244,Lower middle income,4.1,3.5,5.3,5.1,10.6,11.7,11.4,14.6,..,..,..
245,Middle East & North Africa,10.9,7.9,17.2,17.7,22.9,23.0,33.5,38.0,..,..,..
246,Middle East & North Africa (excluding high inc...,11.9,9.5,18.8,19.9,23.6,24.5,34.4,38.7,..,..,..
247,Middle East & North Africa (IDA & IBRD countries),11.9,9.3,18.9,19.6,23.6,24.3,34.5,38.2,..,..,..
248,Middle income,5.1,4.7,5.6,5.7,11.7,12.9,12.9,15.9,..,..,..
249,North America,4.2,4.7,4.4,4.5,10.0,10.5,9.1,8.2,7.5,6.0,3.0
250,Not classified,..,..,..,..,..,..,..,..,..,..,..
251,OECD members,5.8,5.6,7.0,5.9,12.9,12.9,13.4,12.8,12.4,9.1,5.9
252,Other small states,11.4,7.9,16.9,13.7,23.5,19.2,29.9,27.6,..,..,..
253,Pacific island small states,3.6,3.3,4.6,4.2,7.6,8.8,12.2,14.2,..,..,..
254,Post-demographic dividend,6.2,5.8,7.0,5.9,13.8,13.8,13.9,12.4,12.6,9.8,5.5
255,Pre-demographic dividend,6.1,4.9,6.1,5.4,11.8,11.7,12.3,13.3,..,..,..
256,Small states,10.2,7.6,16.1,13.1,21.7,18.6,29.5,27.2,..,..,..
257,South Asia,2.7,2.4,2.5,4.0,7.7,9.1,6.8,12.3,..,..,..
258,South Asia (IDA & IBRD),2.7,2.4,2.5,4.0,7.7,9.1,6.8,12.3,..,..,..
259,Sub-Saharan Africa,7.2,5.8,8.2,6.5,14.0,12.9,15.4,14.4,..,..,..
260,Sub-Saharan Africa (excluding high income),7.2,5.8,8.2,6.5,14.0,12.9,15.4,14.4,..,..,..
261,Sub-Saharan Africa (IDA & IBRD countries),7.2,5.8,8.2,6.5,14.0,12.9,15.4,14.4,..,..,..
262,Upper middle income,5.9,6.0,5.7,6.0,13.1,14.8,14.6,17.8,..,..,..
263,World,5.2,4.8,5.9,5.5,11.9,12.3,12.9,14.8,..,..,..

In [130]:
tables[2]
unemplyment_df= tables[2]
unemplyment_df.columns=columns

In [132]:
unemplyment_df.head(30)

,ShortName,male (% of male labor force) (modeled ILO estimate) 2000,male (% of male labor force) (modeled ILO estimate) 2017,female (% of female labor force) (modeled ILO estimate) 2000,female (% of female labor force) (modeled ILO estimate) 2017,youth male (% of male labor force ages 15-24) (modeled ILO estimate) 2000,youth male (% of male labor force ages 15-24) (modeled ILO estimate) 2017,youth female (% of female labor force ages 15-24) (modeled ILO estimate) 2000,", youth female (% of female labor force ages 15-24) (modeled ILO estimate) 2014-2017",basic education (% of total labor force with basic education) 2014-2017,rmediate education (% of total labor force with intermediate education) 2014-2017,advanced education (% of total labor force with advanced education) 2014-2017
0,Afghanistan,3.8,1.1,3.0,2.5,5.6,2.1,5.2,3.8,12.3,16.2,15.5
1,Albania,17.4,14.6,18.2,12.6,30.0,33.8,26.6,27.5,13.8,20.4,19.1
2,Algeria,29.8,10.0,29.7,21.1,51.3,26.6,47.1,45.5,..,..,..
3,American Samoa,..,..,..,..,..,..,..,..,..,..,..
4,Andorra,..,..,..,..,..,..,..,..,..,..,..
5,Angola,20.7,6.8,25.0,7.5,49.3,16.8,57.1,16.7,..,..,..
6,Antigua and Barbuda,..,..,..,..,..,..,..,..,..,..,..
7,Argentina,14.0,7.5,16.4,9.5,29.8,20.5,36.0,27.4,10.5,9.1,3.3
8,Armenia,8.2,18.1,14.7,17.5,11.7,30.3,15.3,46.3,17.4,17.7,17.8
9,Aruba,..,..,..,..,..,..,..,..,..,..,..
10,Australia,6.5,5.5,6.1,5.7,12.9,13.8,11.2,11.5,..,..,..
11,Austria,4.8,5.9,4.6,5.0,6.9,10.7,5.6,8.7,12.9,5.0,3.1
12,Azerbaijan,11.0,4.1,12.8,5.9,23.7,11.3,21.7,15.6,..,..,..
13,"Bahamas, The",6.2,10.6,8.2,14.4,12.4,20.6,19.4,34.4,..,..,..
14,Bahrain,0.3,0.3,3.7,3.4,1.6,2.0,10.2,12.1,..,..,..
15,Bangladesh,3.3,3.3,3.3,6.7,9.4,10.3,10.3,16.7,3.5,8.5,10.7
16,Barbados,7.4,9.1,11.4,9.9,18.2,26.8,24.1,30.7,..,..,..
17,Belarus,14.0,7.2,9.8,4.0,23.7,11.2,18.9,7.3,13.4,8.2,3.7
18,Belgium,5.3,7.1,8.3,7.1,12.9,20.2,18.3,18.0,13.8,7.1,4.3
19,Belize,7.0,4.7,17.8,15.4,13.6,10.5,31.3,34.3,6.5,9.6,3.9
20,Benin,1.1,2.0,0.5,2.3,1.2,4.2,0.7,4.6,..,..,..
21,Bermuda,..,..,..,..,..,..,..,..,..,..,..
22,Bhutan,1.3,1.6,2.3,3.0,5.0,7.6,6.7,11.4,..,..,..
23,Bolivia,2.9,2.8,4.1,3.8,5.7,6.5,8.7,8.9,2.8,5.0,6.4
24,Bosnia and Herzegovina,23.4,18.8,30.3,23.1,51.4,43.5,59.9,51.0,22.9,11.1,9.8
25,Botswana,14.8,14.4,17.3,21.4,30.6,30.1,36.0,44.0,..,..,..
26,Brazil,7.9,11.4,12.8,14.7,15.0,25.7,23.3,33.2,15.4,14.6,7.0
27,British Virgin Islands,..,..,..,..,..,..,..,..,..,..,..
28,Brunei Darussalam,4.4,8.8,7.3,10.0,16.0,30.0,20.8,29.9,10.4,9.9,7.5
29,Bulgaria,16.6,6.4,15.8,5.9,35.8,13.2,29.6,12.4,17.5,5.3,3.0